name: run-tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pest:
    name: Tests (Pest)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        php: [ 8.1 ]
        stability: [prefer-lowest, prefer-stable]

    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: vendor/bin/pest